### PR TITLE
Chose formatting settings that matched current formatting as much as possible

### PR DESCRIPTION
**Pull request by jhoek**
Note that this pull request does not include any "functional changes".

### CODE REVIEW

**Comment by jhoek** [comment]
Resolves #23.

**Comment by rvanbekkum** [comment]
Looks good. 😊 Do you know if it is possible to have `else` and `elseif` statements on a new line?

**Comment by jhoek** [comment]
I guess the easiest way to control these things is to set `powershell.codeFormatting.preset`. For examples of the different options, please take a look at https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/81. Please let me which style you prefer, and I'll update my pull request.

**Comment by rvanbekkum** [comment]
Then I think my preference would be to use OTBS, but with the `else` on a new line. 😅
Luckily I am not the only one:
https://github.com/PoshCode/PowerShellPracticeAndStyle/issues/81#issuecomment-285871306

**Comment by jhoek** [comment]
I'm not sure if that's something that can be done, and, if I'm entirely honest, I fail to see the benefit. How about if we opt for the OTBS for now, and consider making an exception for `else` later?

**Comment by rvanbekkum** [comment]
Yes, sounds good to me. 😉

**Comment by jhoek** [comment]
In that case, I guess you could approve this PR? :-)

**Comment by rvanbekkum** [comment]
Surely. 😊

**Pull request merged**
